server.port=8090

spring.application.name=payment-validation-service

spring.profiles.active=local

spring.config.import=configserver:http://localhost:8888

# Enable Circuit Breaker metrics in Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.access=unrestricted
management.health.circuitbreakers.enabled=true

management.endpoint.health.show-details=always




# Resilience4j Circuit Breaker configurations
resilience4j.circuitbreaker.instances.payment-validation-service.failureRateThreshold=40
resilience4j.circuitbreaker.instances.payment-validation-service.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.payment-validation-service.waitDurationInOpenState=300s
resilience4j.circuitbreaker.instances.payment-validation-service.register-health-indicator=true
resilience4j.circuitbreaker.instances.payment-validation-service.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.payment-validation-service.permittedNumberOfCallsInHalfOpenState=2

resilience4j.circuitbreaker.instances.payment-validation-service.slidingWindowSize=10
resilience4j.circuitbreaker.instances.payment-validation-service.slidingWindowType=COUNT_BASED


#management:
#endpoints:
#web:
#exposure:
#include: "*"
#endpoint:
#health:
#show-details: always
#enabled: true
#health:
#circuitbreakers:
#enabled: true